@startuml "OOP Project - Class Diagram"

skinparam classAttributeIconSize 0
skinparam classFontSize 11
skinparam defaultFontSize 10
skinparam linetype ortho

' ============================================================
' MATH
' ============================================================
package "math" {
    class vec2 {
        - float x
        - float y
        + vec2(float X, float Y)
        + {static} float dot_product(vec2, vec2)
        + {static} float cross_product(vec2, vec2)
        + float len()
        + float sqr_len()
        + vec2 normalized()
        + vec2 perpendicular()
        + float angle()
        + {static} float angle_between(vec2, vec2)
        + {static} vec2 rotate(vec2, float)
    }

    class vec3 {
        - float x
        - float y
        - float z
        + vec3(float X, float Y, float Z)
        + vec3(vec2 flat, float Z)
        + {static} float dot_product(vec3, vec3)
        + {static} vec3 cross_product(vec3, vec3)
        + float len()
        + float sqr_len()
        + vec3 normalized()
    }

    class segment {
        - vec2 point0
        - vec2 point1
        + segment(vec2 p0, vec2 p1)
        + float angle()
        + vec2 midpoint()
        + float len()
    }

    class ray2 {
        + vec2 end
        + vec2 direction
        + ray2(vec2 e, vec2 d)
        + {static} ray2 rotate(ray2, float)
        + bool intersects(segment, vec2&, float&, float&)
    }

    vec2 -- vec3 : conversion
    segment *-- "2" vec2
    ray2 *-- "2" vec2
}

' ============================================================
' UTIL
' ============================================================
package "util" {
    abstract class resource {
        + {abstract} void* beginning()
        + {abstract} void* end()
        + {abstract} size_t size()
    }

    class binary_resource {
        - void* begin_ptr
        - void* end_ptr
        - size_t byte_size
        + binary_resource(void*, void*)
    }

    class file_resource {
        - vector<byte> file_data
        + file_resource(vector<byte>)
    }

    class resource_loader {
        - unordered_map<string, void*> symbol_cache
        - unordered_map<string, unique_ptr<resource>> resource_cache
        + resource* lookup_resource(string_view)
    }

    class "indexed_storage<T>" as indexed_storage {
        # vector<T> objects
        # vector<id_t> lookup
        # vector<size_t> reverse
        # id_t next_id
        + id_t add(T)
        + void remove(id_t)
        + T& operator[](id_t)
        + bool contains(id_t)
        + id_t size()
    }

    class "componentized<T>" as componentized {
        + auto& operator()(component_tag<field>)
    }

    resource <|-- binary_resource
    resource <|-- file_resource
    resource_loader o-- "*" resource
}

' ============================================================
' ASSETS
' ============================================================
package "assets" {
    class texture {
        - vector<uint32_t> pixels
        - uint32_t width
        - uint32_t height
        - bool has_transparency
        + {static} texture load_from_bin(resource)
    }

    class audio_clip {
        - vector<uint8_t> pcm_data
        - audio_format format
        - unsigned long total_frames
        + {static} audio_clip load_from_bin(resource)
    }

    class menu_element {
        - int function
        - float begin_x, begin_y, end_x, end_y
        - texture_id bg
        - string fmt_template
        + {static} menu_element load_from_bin(resource)
        + int render(renderer_2d, vector<texture>, int, int, mouse_state)
    }

    class menu {
        - vector<menu_element> elements
        - texture_id bg
        + {static} menu load_from_bin(resource_loader, resource)
        + void selective_formatter(string_view, function)
        + int display(renderer_2d, rendering_backend, input_backend, vector<texture>)
    }

    class asset_pack {
        - vector<texture> wall_textures
        - vector<texture> sprite_textures
        - vector<texture> flat_textures
        - vector<texture> ui_textures
        - vector<menu> menus
        - vector<audio_clip> audio_clips
        + {static} asset_pack load(resource_loader, string_view)
        + texture& wall_tx_by_id(texture_id)
        + texture& sprite_tx_by_id(texture_id)
        + texture& flat_tx_by_id(texture_id)
        + texture& ui_tx_by_id(texture_id)
    }

    class asset_manager {
        - resource_loader& rl
        - vector<asset_pack> asset_packs
        - unsigned int cur_set
        + {static} asset_manager load(resource_loader)
        + void cycle_set()
        + texture& wall_tx_by_id(texture_id)
        + texture& sprite_tx_by_id(texture_id)
        + texture& flat_tx_by_id(texture_id)
        + texture& ui_tx_by_id(texture_id)
    }

    menu *-- "*" menu_element
    asset_pack *-- "*" texture
    asset_pack *-- "*" menu
    asset_pack *-- "*" audio_clip
    asset_manager *-- "*" asset_pack
    asset_manager --> util.resource_loader
}

' ============================================================
' AUDIO
' ============================================================
package "audio" {
    class audio_format <<struct>> {
        + unsigned int sample_rate
        + unsigned int channels
        + unsigned int bits_per_sample
    }

    abstract class audio_backend {
        + {abstract} bool open(audio_format)
        + {abstract} void close()
        + {abstract} long write(void*, unsigned long)
        + {abstract} void drain()
        + {abstract} void pause()
        + {abstract} void resume()
        + {abstract} bool bad()
    }

    class audio_mixer {
        - audio_backend& target
        - audio_format mix_format
        - vector<playing_sound> active_sounds
        + audio_mixer(audio_backend, audio_format)
        + void play(audio_clip)
        + void stop_all()
        + void step(unsigned long)
        + bool is_silent()
    }

    package "alsa" {
        class "alsa::backend" as alsa_backend {
            - bool is_bad
            - snd_pcm_t* pcm_handle
            - audio_format fmt
            - bool paused
            + bool open(audio_format)
            + void close()
            + long write(void*, unsigned long)
        }
    }

    audio_backend <|-- alsa_backend
    audio_mixer --> audio_backend
    audio_mixer ..> assets.audio_clip : plays
    audio_backend ..> audio_format
}

' ============================================================
' INPUT
' ============================================================
package "input" {
    enum key {
        a .. z
        n0 .. n9
        f1 .. f12
        ...
    }

    class mouse_state <<struct>> {
        + int x
        + int y
        + bool left
        + bool right
        + bool middle
    }

    abstract class input_backend {
        # bool bad
        + {abstract} void update()
        + {abstract} bool is_key_down(key)
        + {abstract} mouse_state get_mouse_state()
        + {abstract} void reset_mouse_state()
        + {static} key to_key(char)
    }

    package "evdev" {
        class "evdev::backend" as evdev_backend {
            - vector<device_node> devices
            - bitset<KEY_CNT> key_map
            - mouse_state mouse
            - int epoll_fd
            + void update()
            + bool is_key_down(key)
            + mouse_state get_mouse_state()
        }
    }

    input_backend <|-- evdev_backend
}

' ============================================================
' RENDERING
' ============================================================
package "rendering" {
    class sprite {
        # vec2 pos
        # float z_pos
        # texture_id tex_id
        # float inherent_scale
        + sprite(vec2, float, texture_id, float)
    }

    abstract class rendering_mode {
        + {abstract} unsigned int x_res()
        + {abstract} unsigned int y_res()
        + {abstract} unsigned int refresh_hz()
        + {abstract} bool has_vsync()
    }

    abstract class rendering_backend {
        + {abstract} bool bad()
        + {abstract} vector<unique_ptr<rendering_mode>> modes()
        + {abstract} void push_mode(unique_ptr<rendering_mode>)
        + {abstract} unsigned int width()
        + {abstract} unsigned int height()
        + {abstract} unsigned int pitch()
        + {abstract} uint32_t* mmio()
        + {abstract} void wait_for_vsync()
        + {abstract} void flush()
    }

    class renderer_2d {
        - rendering_backend& target
        - asset_manager& tex_manager
        - texture& font_texture
        + renderer_2d(rendering_backend, asset_manager, texture)
        + void draw_texture(texture, int, int, int, int)
        + void draw_text(string_view, int, int, int, int, uint32_t)
        + void draw_rect(int, int, int, int, uint32_t)
    }

    class frame_rendering_data <<struct>> {
        + vec2 cam_pos
        + float cam_height
        + float cam_angle
        + unsigned int sw, sh
        + float fov_scale
        + uint32_t* mmio
    }

    class lighting {
        + {static} int calculate(uint8_t, float)
        + {static} uint32_t apply(uint32_t, int)
    }

    class vissprite {
        - float depth
        - int cx1, cx2
        - float proj_x, scale
        - texture_id tex_id
        - uint8_t light_level
        + vissprite(sprite, float, int, int, float, float, uint8_t, vector<int>, vector<int>)
        + {static} void pa_sort(vector<vissprite>)
        + void render(asset_manager, frame_rendering_data)
    }

    class visplane {
        - float height
        - texture_id tex_id
        - uint8_t light_level
        - int min_x, max_x
        - vector<int> top, bottom
        + {static} void add_column(vector<visplane>&, int, int, int, unsigned int, float, texture_id, uint8_t)
        + void render(asset_manager, frame_rendering_data)
    }

    class software_renderer {
        - rendering_backend& target
        - asset_manager& tex_manager
        - map_data& current_map
        - vector<int> upper_clip, lower_clip
        - vector<visplane> visplanes
        - vector<vissprite> vissprites
        + software_renderer(rendering_backend, asset_manager, map_data)
        + void render_bsp(vec2, float, float, float)
        - void render_bsp_node(id_t, frame_rendering_data)
        - void project_and_draw_linedef(linedef, frame_rendering_data)
        - void render_visplanes(frame_rendering_data)
        - void render_vissprites(frame_rendering_data)
    }

    package "drm_kms" {
        class device_context {
            - int fd
            + device_context(string)
            + bool is_valid()
            + int ioctl(unsigned long, void*)
        }

        class "drm_kms::mode" as drm_mode {
            - drm_mode_modeinfo kernel_mode
            + unsigned int x_res()
            + unsigned int y_res()
            + unsigned int refresh_hz()
        }

        class crtc {
            - device_context& dev
            - uint32_t crtc_id
            + bool set_config(uint32_t, uint32_t, mode)
            + bool page_flip(uint32_t)
        }

        class connector {
            - device_context& dev
            - uint32_t connector_id
            - uint32_t encoder_id
            + vector<unique_ptr<mode>> probe_modes()
            + bool apply_config(crtc, framebuffer, mode)
        }

        class framebuffer {
            - device_context& dev
            - uint32_t handle
            - uint32_t fb_id
            - uint32_t* mmio_ptr
            - size_t size
            + void copy_from(uint32_t*, size_t)
            + bool flip_onto(crtc)
        }

        class "drm_kms::backend" as drm_backend {
            # unique_ptr<device_context> dev
            # unique_ptr<connector> active_connector
            # unique_ptr<crtc> active_crtc
            # unique_ptr<framebuffer> buffers[2]
            # unique_ptr<mode> current_mode
            + bool bad()
            + void push_mode(unique_ptr<rendering_mode>)
            + void flush()
        }

        drm_backend *-- device_context
        drm_backend *-- connector
        drm_backend *-- crtc
        drm_backend *-- "2" framebuffer
        drm_backend *-- drm_mode
        crtc --> device_context
        connector --> device_context
        framebuffer --> device_context
    }

    rendering_backend <|-- drm_backend
    rendering_mode <|-- drm_mode
    renderer_2d --> rendering_backend
    renderer_2d --> assets.asset_manager
    software_renderer --> rendering_backend
    software_renderer --> assets.asset_manager
    software_renderer *-- "*" vissprite
    software_renderer *-- "*" visplane
    vissprite ..> sprite
    vissprite ..> frame_rendering_data
    visplane ..> frame_rendering_data
    sprite --> math.vec2
}

' ============================================================
' SYSTEMS
' ============================================================
package "systems" {
    class health_system {
        - float current_hp
        - float max_hp
        - float armor
        - float max_armor
        - vector<unique_ptr<status_effect>> active_effects
        + health_system(float, float, float, float)
        + void apply_damage(float)
        + void apply_heal(float)
        + void apply_shield(float)
        + void apply_true_damage(float)
        + void add_effect(unique_ptr<status_effect>, actor&)
        + void process_effects(float, actor&)
        + bool is_dead()
    }
}

' ============================================================
' COMBAT
' ============================================================
package "combat" {
    abstract class status_effect {
        # float duration
        # unsigned int intensity
        # float tick_interval
        # float tick_timer
        + status_effect(float, float, unsigned int)
        + {abstract} void on_apply(actor&)
        + {abstract} void on_expire(actor&)
        + {abstract} void affect(actor&)
        + bool tick(float)
        + bool is_expired()
    }

    class burning {
        + burning(float, unsigned int)
        + void affect(actor&)
    }

    class charmed {
        + charmed(float, unsigned int)
        + void on_apply(actor&)
        + void on_expire(actor&)
    }

    class slowed {
        + slowed(float, unsigned int)
        + void on_apply(actor&)
        + void on_expire(actor&)
    }

    status_effect <|-- burning
    status_effect <|-- charmed
    status_effect <|-- slowed

    package "weapons" {
        abstract class firing_mode {
            + {abstract} void spawn_bullet(vec2, float, float)
        }

        class hitscan_firing_mode {
            - map_data& map
            - world& world_ref
            - float max_range
            - float hit_radius
            + hitscan_firing_mode(map_data, world, float, float)
            + void spawn_bullet(vec2, float, float)
        }

        abstract class weapon {
            # unique_ptr<firing_mode> ammo
            # int ammo_count
            # int max_ammo
            # int reserve_mags
            # float fire_rate
            # float last_shot_time
            # float damage
            # weapon(unique_ptr<firing_mode>, int, float, float, int)
            + bool can_fire()
            + void tick(float)
            + void resupply(int)
            + void fire(vec2, float)
            + void reload()
        }

        class pistol {
            + pistol(map_data, world)
        }

        class rifle {
            + rifle(map_data, world)
        }

        class shotgun {
            - {static} int pellet_count = 8
            - {static} float spread
            + shotgun(map_data, world)
            + void fire(vec2, float)
        }

        class smg {
            + smg(map_data, world)
        }

        class sniper_rifle {
            + sniper_rifle(map_data, world)
        }

        class katana {
            + katana()
            + bool can_fire()
            + void fire(vec2, float)
            + void reload()
        }

        class plasma_gun {
            + plasma_gun(map_data, world)
        }

        firing_mode <|-- hitscan_firing_mode
        weapon *-- firing_mode
        weapon <|-- pistol
        weapon <|-- rifle
        weapon <|-- shotgun
        weapon <|-- smg
        weapon <|-- sniper_rifle
        weapon <|-- katana
        weapon <|-- plasma_gun
    }
}

systems.health_system *-- "*" combat.status_effect

' ============================================================
' ENGINE
' ============================================================
package "engine" {
    abstract class entity {
        + {abstract} void update(float dt)
    }

    enum faction {
        player
        enemy
        neutral
    }

    class renderable_entity {
        + renderable_entity(vec2, float, texture_id, float)
    }

    class actor {
        # health_system health
        # float angle
        # float movement_speed
        # faction team
        + actor(vec2, float, texture_id, float, float, float, float, faction)
        + void take_damage(float)
        + void take_true_damage(float)
        + void heal(float)
        + void add_shield(float)
        + void add_effect(unique_ptr<status_effect>)
        + bool is_dead()
        + void update(float)
    }

    class world {
        - indexed_storage<unique_ptr<entity>> entities
        - vector<id_t> deleted_entities
        + world()
        + void update(float)
        + entity& operator[](id_t)
        + id_t register_entity(unique_ptr<entity>)
        + void delete_entity(id_t)
        + entity* entity_from_id(id_t)
    }

    entity <|-- renderable_entity
    rendering.sprite <|-- renderable_entity
    renderable_entity <|-- actor
    actor *-- systems.health_system
    actor --> faction
    world *-- "*" entity
}

' ============================================================
' ENTITIES
' ============================================================
package "entities" {
    class player {
        # vector<unique_ptr<weapon>> weapons
        # float sensitivity
        # int current_weapon_index
        + player(vec2, float, texture_id, float, float, float, float, float)
        + void update(float)
        + void move(vec2)
        + void rotate(float)
        + void shoot()
        + void reload()
        + void switch_weapons(int)
        + bool resupply<WeaponT>(int)
    }

    class monster {
        # actor* target_ptr
        # float attack_cooldown
        # float attack_range
        # float detection_radius
        # float attack_damage
        # float attack_cd_max
        + monster(...)
        # bool has_target()
        # float dist_to_target()
        # vec2 dir_to_target()
        # void move_toward_target(float, float)
        # void move_away_from_target(float, float)
        # void strafe(float, float)
        # void melee_attack(float)
        + void update(float)
    }

    engine.actor <|-- player
    engine.actor <|-- monster
    player *-- "*" combat.weapons.weapon

    package "monsters" {
        class monster_basic {
            + monster_basic(vec2, float, actor*)
            + void update(float)
        }

        class monster_all_rounder {
            - bool melee_mode
            - float melee_threshold
            + monster_all_rounder(vec2, float)
            + void update(float)
        }

        class monster_assault {
            - int burst_size
            - float burst_interval
            - int burst_remaining
            - float burst_timer
            - float strafe_sign
            + monster_assault(vec2, float)
            + void update(float)
        }

        class monster_boss {
            - int current_phase
            - float max_hp_val
            - bool is_charging
            - float charge_timer
            - bool is_channeling
            - world& world_ref
            - map_data& map_ref
            + monster_boss(vec2, float, world&, map_data&)
            + bool channeling()
            + float flash_phase()
            + void update(float)
            - void phase1_ai(float, float)
            - void phase2_ai(float, float)
            - void phase3_ai(float, float)
        }

        class monster_Duzy_Gruby {
            + monster_Duzy_Gruby(vec2, float)
            + void update(float)
        }

        class monster_elite_swift {
            - float charge_speed
            - bool is_charging
            - float circle_angle
            + monster_elite_swift(vec2, float)
            + void update(float)
        }

        class monster_elite_tank {
            - bool melee_mode
            - float melee_threshold
            - float heavy_timer
            + monster_elite_tank(vec2, float)
            + void update(float)
        }

        class monster_magic {
            - float charge_time
            - float charge_timer
            - bool is_charging
            + monster_magic(vec2, float)
            + void update(float)
        }

        class monster_Maly_Szybki {
            - bool is_dashing
            - float dash_timer
            - float dash_cooldown
            + monster_Maly_Szybki(vec2, float)
            + void update(float)
        }

        class monster_ranged {
            - float preferred_dist
            + monster_ranged(vec2, float)
            + void update(float)
        }

        class monster_sniper {
            - float shoot_interval
            - float aim_timer
            + monster_sniper(vec2, float)
            + void update(float)
        }

        class monster_spawner {
            - int max_spawns
            - int current_spawns
            - float spawn_interval
            + monster_spawner(vec2, float)
            + void update(float)
        }

        class monster_trapper {
            - int max_traps
            - int traps_placed
            - float trap_interval
            + monster_trapper(vec2, float)
            + void update(float)
        }

        monster <|-- monster_basic
        monster <|-- monster_all_rounder
        monster <|-- monster_assault
        monster <|-- monster_boss
        monster <|-- monster_Duzy_Gruby
        monster <|-- monster_elite_swift
        monster <|-- monster_elite_tank
        monster <|-- monster_magic
        monster <|-- monster_Maly_Szybki
        monster <|-- monster_ranged
        monster <|-- monster_sniper
        monster <|-- monster_spawner
        monster <|-- monster_trapper
    }
}

' ============================================================
' GEOMETRY
' ============================================================
package "geometry" {
    class sector {
        - float floor_height
        - float ceiling_height
        - texture_id floor_tex
        - texture_id ceiling_tex
        - uint8_t light_level
        + sector(float, float, texture_id, texture_id, uint8_t)
        + {static} vector<sector> load_from_bin(resource)
    }

    class sidedef {
        - id_t facing_sector
        - texture_id upper_tex
        - texture_id middle_tex
        - texture_id lower_tex
        + sidedef(id_t, texture_id, texture_id, texture_id)
        + {static} vector<sidedef> load_from_bin(resource)
    }

    class linedef {
        - segment seg
        - id_t front
        - id_t back
        + linedef(vec2, vec2, id_t, id_t)
        + {static} vector<linedef> load_from_bin(resource)
        + bool is_wall()
        + bool is_portal()
        + vec2 dir()
        + float len()
    }

    class subsector {
        - vector<id_t> lines
        - vector<unique_ptr<sprite>> sprites
        + {static} vector<subsector> load_from_bin(resource)
        + unique_ptr<sprite> remove_sprite(sprite*)
        + void add_sprite(unique_ptr<sprite>)
    }

    class bsp_node {
        - vec2 pl_coord
        - vec2 pl_dir
        - bounding_box front_box
        - bounding_box back_box
        - id_t front
        - id_t back
        + bool is_pt_front_side(vec2)
        + bool is_front_leaf()
        + bool is_back_leaf()
        + {static} vector<bsp_node> load_from_bin(resource)
    }

    class map_data {
        + indexed_storage<sector> sectors
        + indexed_storage<sidedef> sidedefs
        + indexed_storage<linedef> linedefs
        + indexed_storage<subsector> subsectors
        + indexed_storage<bsp_node> nodes
        + id_t root_node_id
        + id_t get_subsector_id(vec2)
        + void move_to(sprite*, vec2)
        + {static} map_data load_from_bin(resource, resource, resource, resource, resource)
    }

    sidedef --> sector : facing_sector
    linedef --> sidedef : front/back
    linedef *-- math.segment
    subsector --> linedef : lines
    subsector *-- "*" rendering.sprite
    map_data *-- "*" sector
    map_data *-- "*" sidedef
    map_data *-- "*" linedef
    map_data *-- "*" subsector
    map_data *-- "*" bsp_node
    bsp_node --> math.vec2
}

' ============================================================
' WORLD OBJECTS
' ============================================================
package "world_object" {
    abstract class pickup {
        - vec2 position
        - float pickup_radius
        - player& player_ref
        - world& world_ref
        - id_t self_id
        + pickup(vec2, player&, world&, id_t, float)
        + void update(float)
        + bool in_range(vec2)
        + {abstract} void on_pickup(player&)
    }

    class health_pickup {
        - float heal_amount
        + health_pickup(vec2, float, player&, world&, id_t, float)
        + void on_pickup(player&)
    }

    class armor_pickup {
        - float armor_amount
        + armor_pickup(vec2, float, player&, world&, id_t, float)
        + void on_pickup(player&)
    }

    class weapon_pickup {
        - unique_ptr<weapon> provided_weapon
        + weapon_pickup(vec2, unique_ptr<weapon>, player&, world&, id_t, float)
        + void on_pickup(player&)
    }

    engine.entity <|-- pickup
    pickup <|-- health_pickup
    pickup <|-- armor_pickup
    pickup <|-- weapon_pickup
    pickup --> entities.player
    pickup --> engine.world
    weapon_pickup *-- combat.weapons.weapon
}

' ============================================================
' GAME
' ============================================================
package "game_pkg" {
    class game {
        - resource_loader rl
        - asset_manager am
        - unique_ptr<input_backend> input
        - unique_ptr<rendering_backend> rb
        - unique_ptr<audio_backend> ab
        - map_data md
        - audio_mixer mix
        - renderer_2d r2d
        - software_renderer sr
        - world w
        - float fov
        + game()
        + void run()
        - void text_scroll(vector<string>, audio_clip_id)
        - void opening()
        - void ending()
        - void credits()
        - void show_main_menu()
        - void show_options()
        - void loop()
    }

    game *-- util.resource_loader
    game *-- assets.asset_manager
    game *-- input.input_backend
    game *-- rendering.rendering_backend
    game *-- audio.audio_backend
    game *-- geometry.map_data
    game *-- audio.audio_mixer
    game *-- rendering.renderer_2d
    game *-- rendering.software_renderer
    game *-- engine.world
}

' ============================================================
' CROSS-PACKAGE RELATIONSHIPS
' ============================================================
combat.weapons.hitscan_firing_mode --> geometry.map_data
combat.weapons.hitscan_firing_mode --> engine.world
entities.monsters.monster_boss --> engine.world
entities.monsters.monster_boss --> geometry.map_data
entities.monster --> engine.actor : target_ptr
rendering.software_renderer --> geometry.map_data

@enduml
