#!/usr/bin/expect -f

log_user 0

set timeout 2

spawn ./tests/resource.out

expect "READY"

proc run_test {cmd expected {quiet 0}} {
    global expect_out

    send "$cmd\r"
    expect -re {RESULT ([0-9]+)}
    set result $expect_out(1,string)

    if {$result == $expected} {
        if {$quiet == 0} {
            #puts "PASS ($cmd)"
        }
    } else {
        puts "FAIL ($cmd)"
        puts "\tGot:      $result"
        puts "\tExpected: $expected"
        exit 1
    }
}

proc run_dump_test {cmd expected {quiet 0}} {
    global expect_out

    send "$cmd\r"
    expect -re {RESULT ([^\r\n]*)}
    set result $expect_out(1,string)

    if {$result == $expected} {
        if {$quiet == 0} {
            #puts "PASS ($cmd)"
        }
    } else {
        puts "FAIL ($cmd)"
        puts "\tGot:      '$result'"
        puts "\tExpected: '$expected'"
        exit 1
    }
}

run_test "lookup hello-world.txt"     14
run_test "lookup meta-flat"           20
run_test "lookup meta-sprite"         33
run_test "lookup meta-walls"          44
run_test "lookup flat-font-atlas.btx" 196620
run_test "lookup wall-test.btx"       5000012
run_test "lookup wall-test2.btx"      7704412
run_test "lookup wall-test3.btx"      12800012

run_dump_test "dump hello-world.txt" "Hello, World!"
run_dump_test "dump hello-world.txt" "Hello, World!"
run_dump_test "dump hello-world.txt" "Hello, World!"

run_test "lookup hello-world.txt" 14

send "exit\r"
expect eof

puts "PASS resource tests"
